---
- name: Package installer
  become: true
  hosts: my_group

  tasks:
    - name: Check if packages are installed
      package_facts:
        manager: auto
      register: package_info
      failed_when: package_info.failed

    - name: Install packages
      package:
        name:
          - my_package_1
          - my_package_2
        state: present
      register: result
      failed_when: result.failed
      when: "'my_package_1' not in ansible_facts.packages or 'my_package_2' not in ansible_facts.packages"

